### ISSUE TITLE
Add Ctrl+comma for creating autowired private field by variable name.

### ISSUE THREAD

**Issue by kalmykov-sergey** [viartemev/requestmapper#1]
Just typing 
```
myFavoriteService. (here press hotkey to add new autowired MyFavoriteServcie.class dependency)
```
This small feature can make this plugin more popular and more time-saving!

But urls are awesome! This is VERY useful! Thank you!

**Comment by viartemev** [comment]
I think it's good idea for new plugin, but this plugin only for request mapping
