### ISSUE TITLE
No match root GET url if exist least one method with same PathVariable 

### ISSUE THREAD

**Issue by selectee** [viartemev/requestmapper#127]
### Issue (required)

```java
@RestController
@RequestMapping("/bug/session")
public class Session2Controller {

    @RequestMapping(value = "/getSessionDetailedCounts/{sessionId}/", method = RequestMethod.GET)
    @ResponseStatus(HttpStatus.OK)
    @ResponseBody
    public SessionDetailedCountsInfo getSessionDetailedCounts2(@PathVariable("sessionId") Long sessionId) {
        return null;
    }

    @RequestMapping(value = "/{sessionId}", method = RequestMethod.GET)
    @ResponseStatus(HttpStatus.OK)
    @ResponseBody
    public SessionDto getSessionById(@PathVariable("sessionId") Long sessionId) {
        return null;
    }

}

```
### Specifications (required)

  - Version of the plugin: 0.14
  - IntelliJ IDEA version:
IntelliJ IDEA 2018.2 (Ultimate Edition)
Build #IU-182.3684.101, built on July 24, 2018

JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

![image](https://user-images.githubusercontent.com/11858038/43630878-3a526898-970a-11e8-861c-9d166e88e235.png)

**Comment by viartemev** [comment]
Will be fixed in version `0.15.0`
