### ISSUE TITLE
Add a tool window to show all restful url ?

### ISSUE THREAD

**Issue by gonnalee** [viartemev/requestmapper#16]
Adding a tool window to show all restful url  is better。we can also use the shortcut key to search ，but sometimes I would like to view all mappings in tool window.

**Comment by viartemev** [comment]
@gonnalee I think, it's a cool feature, but you can find this one in [IDEA](https://blog.jetbrains.com/idea/2017/11/whats-new-in-intellij-idea-2017-3-for-spring-boot/) (Support for Spring Boot 2.0 feature). You should run an app in debug mode.
Anyway, feel free to create PR for it :)
