### ISSUE TITLE
Feature request: Variables in spring urls

### ISSUE THREAD

**Issue by K-4U** [viartemev/requestmapper#30]
For our project we have a lot of variables in url, for example: 
`/get/by-catalog/{catalog}/by-id/{id}`
It would be really helpful if i could paste an url that has data filled in:
`/get/by-catalog/cars/by-id/24` 
And still have the plugin realise it has to go to a certain method. Right now it doesn't find anything.

**Comment by viartemev** [comment]
@K-4U can you test last master version?

**Comment by K-4U** [comment]
I will give it a try tomorrow when i'm back at work! Thank you! :D
What will be the best method for me to get it into IntelliJ?

**Comment by viartemev** [comment]
@K-4U execute `./gradlew buildPlugin` command and you can find plugin jar in `build/distributions/`.
(You can install plugin from disk)[https://www.jetbrains.com/help/idea/installing-a-plugin-from-the-disk.html]

**Comment by K-4U** [comment]
Finally got around to trying it. It works beautifully! Thank you so much!

**Comment by viartemev** [comment]
Plugin was loaded to [JetBrains repo](https://plugins.jetbrains.com/plugin/9567-request-mapper/update/40262)
