### ISSUE TITLE
Search for /{id} works in an unexpected way

### ISSUE THREAD

**Issue by php-coder** [viartemev/requestmapper#49]
When I search for `{id}` it shows me all mapping that have `{id}` argument.
But when I'm searching for `/{id}` it returns unexpected results. For examples, in my case, the first item is "GET /account/activate/key/{key}". Also it contains items like `/category/{slug}`.

How it searches? Why it shown irrelevant results? Could this logic be improved to not violate [least astonishment principle](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)?

**Comment by asm0dey** [comment]
I would propose following order of suggestions:
1. strict matches
2. startsWith(ignoreCase=true)
3. same number of parts
4. all the other things

**Comment by viartemev** [comment]
@php-coder could you test this build?
[Request mapper-0.9.zip](https://github.com/viartemev/requestmapper/files/1747104/Request.mapper-0.9.zip)

**Comment by viartemev** [comment]
Done
