### ISSUE TITLE
Add full url support

### ISSUE THREAD

**Issue by linux-china** [viartemev/requestmapper#5]
For example, if I visit http://localhost:8080/xx/yyy?id=11 and the server throws 500 exception. I just want request mapper to help me navigate to the code by http url.   just command + shift + back slash, past the http url and navigate to the code.    some problems: 1. keep path part 2. wildcard match

**Comment by viartemev** [comment]
@linux-china I think it's possible, but by using another shortcuts.
If you would like find something like this `localhost:8080/get?param=1` and you has:
- `/get/{id}`
- `/long/get/{id}`
- `/get`
In this case I can't exactly determine which method is used.
Using an exact match can resolve this case, but it will not allow to find by an approximate value.

I think good choice - add new shortcut for **accurate** and **approximate** search.
@linux-china what do you think?

**Comment by linux-china** [comment]
another shortcut is ok :)   thanks for navigation by URL.

**Comment by viartemev** [comment]
@linux-china you can test approximate part of this feature in `0.3.1` version.
I'm waiting for feedback

**Comment by viartemev** [comment]
@linux-china new version of plugin released! If you think approximate case resolved in new version, tell me, for accurate path I will open new issue
