### ISSUE TITLE
Add support for urls from constants

### ISSUE THREAD

**Issue by winniae** [viartemev/requestmapper#6]
My current project usually uses constant values to define the URL-Patterns for the RequestMapping annotation. This seems not to be supported currently.

e.g.
`public static final String URI_PATTERN = "/myResource";
@RequestMapping(value = URI_PATTERN)`

**Comment by viartemev** [comment]
@winniae, @dchuiko made PR for resolving this issue. I pushed new version of plugin to JetBrains Repository, you can check it after moderation of plugin.
