### ISSUE TITLE
Url resolving doesn't work on class level

### ISSUE THREAD

**Issue by dchuiko** [viartemev/requestmapper#7]
Example:
```
@Controller(value = "/api/bla")
public class LsPaymentController
```
If you try searching for "_api/bla_" you will get empty result.

**Comment by viartemev** [comment]
Value of `@Controller` or `@RestController ` used for indicate a suggestion for a logical component name. 
If you would like add mapping to all method of class, you need add `@RequestMapping` annotation over required class.

**Comment by dchuiko** [comment]
@viartemev My mistake. Let's close this issue as "Won't fix"
