### ISSUE TITLE
PsiBinaryExpressionExtractor.kt:10: deduplicate...

### ISSUE THREAD

**Issue by 0pdd** [viartemev/requestmapper#70]
The puzzle `68-cb6e41c6` from #68 has to be resolved:

https://github.com/viartemev/requestmapper/blob/5528ce653947f6de55769c9ad0378ef2f8e5c30b/src/main/kotlin/com/viartemev/requestmapper/annotations/extraction/PsiBinaryExpressionExtractor.kt#L10-L10

The puzzle was created by Vyacheslav Artemyev on 25-Feb-18. 

Estimate: 0 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by viartemev** [comment]
Done
