### ISSUE TITLE
Search pattern should be case insensitive

### ISSUE THREAD

**Issue by izhangzhihao** [viartemev/requestmapper#74]
<img width="555" alt="screen shot 2018-03-07 at 4 44 16 pm" src="https://user-images.githubusercontent.com/12044174/37082226-e3963eb0-2226-11e8-8b46-a9bcdaa8fa0a.png">
<img width="540" alt="screen shot 2018-03-07 at 4 44 30 pm" src="https://user-images.githubusercontent.com/12044174/37082234-ed48831e-2226-11e8-94ad-d9141b9a7f58.png">

On Intellij-IDEA 2018.1-EAP

**Comment by viartemev** [comment]
@izhangzhihao are you talking about the case only with method name? 
Becuase by default, a path is case sensitive and you need to add special config in Spring for 
handling case insensitive paths.

**Comment by izhangzhihao** [comment]
Yes, in spring the path is case sensitive indeed, but the request method should be case insensitive I think.

**Comment by viartemev** [comment]
@izhangzhihao fix will be in **0.11** version

**Comment by izhangzhihao** [comment]
Great！
________________________________
